knife4j:
  production: false
  enable: true
  basic:
    enable: false
    username: renren
    password: 2ZABCDEUgF
  setting:
    enableFooter: false
spring:
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/xiaozhi_esp32_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: false
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  data:
    redis:
      host: 127.0.0.1         # Redis server address
      port: 6379              # Redis server connection port
      password:              # Redis server connection password (empty by default)
      database: 0            # Redis database index (0 by default)
      timeout: 10000ms       # Connection timeout time (milliseconds)
      lettuce:
        pool:
          max-active: 8      # Maximum connections in connection pool (negative value means no limit)
          max-idle: 8        # Maximum idle connections in connection pool
          min-idle: 0        # Minimum idle connections in connection pool
        shutdown-timeout: 100ms
