# If you only want to install xiaozhi-server lightly, only use local configuration files, ignore this file, do not change anything in this file
# If you want to get configuration from manager-api, please read below:
# Please copy this file to xiaozhi-server/data directory, if there is no data directory, please create one, and rename the copied file to .config.yaml
# Note: if data directory has .config.yaml file, please delete it first
# First start manager-api and manager-web, register an account, the first registered account is the administrator
# Use administrator, enter [Parameter Management] page, find [server.secret], copy it to parameter value, note that server.secret changes every time deployed from scratch
# Open the .config.yaml file in this data directory, modify manager-api.secret to the server.secret copied just now
server:
  ip: 0.0.0.0
  port: 8000
  # HTTP service port, used for vision analysis interface
  http_port: 8003
  # Vision analysis interface address
  # Interface address for vision analysis sent to device
  # If written according to the default method below, the system will automatically generate a vision recognition address and output it in the startup log. You can directly access this address with a browser to confirm
  # When you use docker deployment or public network deployment (using ssl, domain name), it may not be accurate
  # So if you use docker deployment, set vision_explain to local network address
  # If you use public network deployment, set vision_explain to public network address
  vision_explain: http://your_ip_or_domain:port/mcp/vision/explain
manager-api:
  # Your manager-api address, preferably use local network ip
  # If using docker deployment, please fill in as http://xiaozhi-esp32-server-web:8002/xiaozhi
  url: http://127.0.0.1:8002/xiaozhi
  # Your manager-api token, which is the server.secret copied just now
  secret: your_server.secret_value