# Docker Server Installation

version: '3'
services:
  xiaozhi-esp32-server:
    build:
      context: .
      dockerfile: Dockerfile-server
    container_name: xiaozhi-esp32-server
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=UTC
    mem_limit: 4g
    mem_reservation: 2g
    ports:
      # WebSocket server
      - "8000:8000"
      # HTTP service port for simple OTA interface (single service deployment) and visual analysis interface
      - "8003:8003"
    volumes:
      # Configuration file directory
      - ./data:/opt/xiaozhi-esp32-server/data
      # Model file mount, very important
      - ./models/vosk:/opt/xiaozhi-esp32-server/models/vosk
      # Whisper model mount
      - ./models/whisper:/opt/xiaozhi-esp32-server/models/whisper
      # Sherpa ONNX model mounts
      - ./models/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17:/opt/xiaozhi-esp32-server/models/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17
      - ./models/sherpa-onnx-paraformer-zh-small-2024-03-09:/opt/xiaozhi-esp32-server/models/sherpa-onnx-paraformer-zh-small-2024-03-09